In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000

In [7]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[4193, 904, 4085, 9133], [4193, 904, 4085, 3120], [4193, 9777, 4085, 9023], [6753, 7902, 3085, 4350, 2959], [6753, 7902, 3085, 4350, 9538], [1538, 4193, 805, 4085, 5417], [8460, 1771, 7913, 4350]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)#this just makes all the sentences of equal word
print(embedded_docs)

[[   0    0    0    0 4193  904 4085 9133]
 [   0    0    0    0 4193  904 4085 3120]
 [   0    0    0    0 4193 9777 4085 9023]
 [   0    0    0 6753 7902 3085 4350 2959]
 [   0    0    0 6753 7902 3085 4350 9538]
 [   0    0    0 1538 4193  805 4085 5417]
 [   0    0    0    0 8460 1771 7913 4350]]


In [13]:
dim=15

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

[[[ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863
   -0.00103357 -0.00652068  0.04928745 -0.01940929  0.0209108 ]
  [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863
   -0.00103357 -0.00652068  0.04928745 -0.01940929  0.0209108 ]
  [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863
   -0.00103357 -0.00652068  0.04928745 -0.01940929  0.0209108 ]
  [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863
   -0.00103357 -0.00652068  0.04928745 -0.01940929  0.0209108 ]
  [-0.00780408  0.02263955  0.04722646 -0.00559573  0.0084362
    0.00238692 -0.02693908  0.04654462  0.01946895  0.01080273]
  [ 0.03118248 -0.00709962  0.01447656  0.03924019 -0.00307496
   -0.01558598 -0.03726596 -0.03784705  0.01519561  0.02249991]
  [-0.04522938  0.04358435 -0.02639511  0.00818244  0.0280941
    0.01383596  0.01054347 -0.03245822  0.02615546  0.02398381]
  [ 0.03262201 -0.02048428  0.03700374 -0.04197028 -0.03526932
    0.03619776 -0.03620868 -0.00959136 -0.02576649

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 4193,  904, 4085, 9133])

In [18]:
print(model.predict(embedded_docs)[0])

[[ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863 -0.00103357
  -0.00652068  0.04928745 -0.01940929  0.0209108 ]
 [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863 -0.00103357
  -0.00652068  0.04928745 -0.01940929  0.0209108 ]
 [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863 -0.00103357
  -0.00652068  0.04928745 -0.01940929  0.0209108 ]
 [ 0.01923752 -0.02799311  0.03272003 -0.0419863  -0.02059863 -0.00103357
  -0.00652068  0.04928745 -0.01940929  0.0209108 ]
 [-0.00780408  0.02263955  0.04722646 -0.00559573  0.0084362   0.00238692
  -0.02693908  0.04654462  0.01946895  0.01080273]
 [ 0.03118248 -0.00709962  0.01447656  0.03924019 -0.00307496 -0.01558598
  -0.03726596 -0.03784705  0.01519561  0.02249991]
 [-0.04522938  0.04358435 -0.02639511  0.00818244  0.0280941   0.01383596
   0.01054347 -0.03245822  0.02615546  0.02398381]
 [ 0.03262201 -0.02048428  0.03700374 -0.04197028 -0.03526932  0.03619776
  -0.03620868 -0.00959136 -0.02576649  0.04028973]]

In [20]:
#here we have total 10 dimensions as given earlier
#number of lists is 8->sent_length